### ISSUE TITLE
Push notifications to dev chats

### ISSUE THREAD

**Issue by ales-tsurko** [tonikasoft/fpsdk#55]
Notify about (if possible):

* [ ] issue open
* [ ] issue assigns
* [ ] issue comments
* [ ] review requests
* [ ] review submissions
* [x] ~~PR comments~~
* [ ] PR merge

**Comment by ales-tsurko** [comment]
Simple discord webhook ignores some events (issue assigns and review requests, for ex.). May be this will solve the problem: https://github.com/marketplace/actions/discord-webhook-notify

**Comment by AlesTsurko** [comment]
тест
